name: Setup Amoeba

inputs:
  ref:
    description: 'The ref to checkout'
    required: false
    default: 'main'

runs:
  using: "composite"
  steps:
    - name: Checkout deepinthink/amoeba
      uses: actions/checkout@v4
      with:
        repository: deepinthink/amoeba
        path: deepinthink/amoeba
        ref: ${{ inputs.ref }}

    - name: Build && Install amoeba-maven
      shell: bash
      run: cd deepinthink/amoeba/tools/buildtools/java/amoeba-maven && ./mvnw install -B

    - name: Build && Install amoeba-external
      shell: bash
      run: cd deepinthink/amoeba/infrastructure/external/java/amoeba-external && ./mvnw install -B

    - name: Build && Install amoeba-spring-boot
      shell: bash
      run: cd deepinthink/amoeba/infrastructure/framework/java/amoeba-spring-boot && ./mvnw install -B

    - name: Build && Install amoeba-specification-benchmark
      shell: bash
      run: cd deepinthink/amoeba/specification/benchmark/java/amoeba-specification-benchmark && ./mvnw install -B

    - name: Build && Install amoeba-specification-component
      shell: bash
      run: cd deepinthink/amoeba/specification/component/java/amoeba-specification-component && ./mvnw install -B

    - name: Build && Install amoeba-specification-pipeline
      shell: bash
      run: cd deepinthink/amoeba/specification/pipeline/java/amoeba-specification-pipeline && ./mvnw install -B

    - name: Build && Install amoeba-specification-service
      shell: bash
      run: cd deepinthink/amoeba/specification/service/java/amoeba-specification-service && ./mvnw install -B

    - name: Build && Install amoeba-spring-boot-service-admin
      shell: bash
      run: cd deepinthink/amoeba/services/admin/java/amoeba-spring-boot-service-admin && ./mvnw install -B

    - name: Build && Install amoeba-spring-boot-component-config
      shell: bash
      run: cd deepinthink/amoeba/components/config/java/amoeba-spring-boot-component-config && ./mvnw install -B

    - name: Build && Install amoeba-spring-boot-component-job
      shell: bash
      run: cd deepinthink/amoeba/components/job/java/amoeba-spring-boot-component-job && ./mvnw install -B

    - name: Build && Install amoeba-spring-boot-benchmark
      shell: bash
      run: cd deepinthink/amoeba/infrastructure/benchmark/java/amoeba-spring-boot-benchmark && ./mvnw install -B

    - name: Build && Install amoeba-spring-boot-pipeline
      shell: bash
      run: cd deepinthink/amoeba/infrastructure/pipeline/java/amoeba-spring-boot-pipeline && ./mvnw install -B

    - name: Build && Install amoeba-spring-boot-rbac
      shell: bash
      run: cd deepinthink/amoeba/services/rbac/java/amoeba-spring-boot-rbac && ./mvnw install -B

    - name: Build && Install amoeba-benchmark
      shell: bash
      run: cd deepinthink/amoeba/templates/benchmark/java/amoeba-benchmark && ./mvnw install -B

    - name: Build && Install amoeba-devops
      shell: bash
      run: cd deepinthink/amoeba/templates/devops/java/amoeba-devops && ./mvnw install -B

    - name: Build && Install amoeba-initializr
      shell: bash
      run: cd deepinthink/amoeba/tools/initializr/java/amoeba-initializr && ./mvnw install -B
